# Generated by Django 5.1 on 2024-08-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pub_year', models.CharField(max_length=4)),
                ('img_link', models.URLField()),
                ('book_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
